export const categories = [
  'all-machines',
  'all-mail',
  // 'apricorn-balls',
  'apricorn-box',
  'baking-only',
  'catching-bonus',
  'choice',
  'curry-ingredients',
  'dex-completion',
  // 'dynamax-crystals',
  'effort-drop',
  'effort-training',
  'evolution',
  'flutes',
  'healing',
  'held-items',
  'in-a-pinch',
  'jewels',
  'loot',
  'medicine',
  // 'mega-stones',
  // 'memories',
  'mulch',
  'nature-mints',
  // 'picky-healing',
  'plates',
  'pp-recovery',
  'revival',
  // 'scarves',
  'special-balls',
  'species-candies',
  'species-specific',
  'spelunking',
  'standard-balls',
  'stat-boosts',
  'status-cures',
  'training',
  'type-enhancement',
  'type-protection',
  'vitamins',
  // 'z-crystals',
];
